<a href="https://colab.research.google.com/github/FarahBelghith2/PFE/blob/main/Nettoyage_donn%C3%A9es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np

In [2]:

df = pd.read_csv("projet.csv", sep=";", encoding="latin1")
df.head()

,id,date,saison,annee,mois,heure,ferié,jour_semaine,jour_ ouvrable,meteo,temperature,humidite,vent,utilisateurs occasionnels,utilisateurs inscrits,reservations,demande_elevee
0,1,01/01/2011,1,0,1,0,0,6,0,1,0.24,0.81,0.0,3,13,16,0
1,2,01/01/2011,1,0,1,1,0,6,0,1,0.22,0.80,0.0,8,32,40,1
2,3,01/01/2011,1,0,1,2,0,6,0,1,0.22,0.80,0.0,5,27,32,1
3,4,01/01/2011,1,0,1,3,0,6,0,1,0.24,0.75,0.0,3,10,13,0
4,5,01/01/2011,1,0,1,4,0,6,0,1,0.24,0.75,0.0,0,1,1,0

In [3]:
print(df.columns.tolist())

['id', 'date ', 'saison', 'annee', 'mois', 'heure', 'ferié', 'jour_semaine', 'jour_ ouvrable', 'meteo', 'temperature', 'humidite', 'vent', 'utilisateurs occasionnels', 'utilisateurs inscrits', 'reservations', 'demande_elevee']

In [4]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("[^0-9a-zA-Z_]", "", regex=True)
)

print(df.columns.tolist())

['id', 'date', 'saison', 'annee', 'mois', 'heure', 'feri', 'jour_semaine', 'jour__ouvrable', 'meteo', 'temperature', 'humidite', 'vent', 'utilisateurs_occasionnels', 'utilisateurs_inscrits', 'reservations', 'demande_elevee']

In [5]:
df = df.rename(columns={"jour__ouvrable": "jour_ouvrable"})

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         17379 non-null  int64
 1   date                       17379 non-null  object
 2   saison                     17379 non-null  int64
 3   annee                      17379 non-null  int64
 4   mois                       17379 non-null  int64
 5   heure                      17379 non-null  int64
 6   feri                       17379 non-null  int64
 7   jour_semaine               17379 non-null  int64
 8   jour_ouvrable              17379 non-null  int64
 9   meteo                      17379 non-null  int64
 10  temperature                17379 non-null  float64
 11  humidite                   17379 non-null  float64
 12  vent                       17379 non-null  float64
 13  utilisateurs_occasionnels  17379 non-null  int64
 14  utilisateurs_inscrits      17379 non-null  int64
 15  reservations               17379 non-null  int64
 16  demande_elevee             17379 non-null  int64
dtypes: float64(3), int64(13), object(1)
memory usage: 2.3+ MB

In [9]:
df = df.rename(columns={"feri": "ferie"})

In [10]:
print(df.columns.tolist())

['id', 'date', 'saison', 'annee', 'mois', 'heure', 'ferie', 'jour_semaine', 'jour_ouvrable', 'meteo', 'temperature', 'humidite', 'vent', 'utilisateurs_occasionnels', 'utilisateurs_inscrits', 'reservations', 'demande_elevee']

In [11]:
df = df[[
    "date",
    "saison",
    "heure",
    "jour_semaine",
    "ferie",
    "jour_ouvrable",
    "meteo",
    "temperature",
    "humidite",
    "vent",
    "reservations"
]]

In [12]:
df["is_special_event"] = 0

In [13]:
dates_existantes = sorted(df["date"].dropna().unique())
print(dates_existantes[:20])

['01/01/2011', '01/01/2012', '01/02/2011', '01/02/2012', '01/03/2011', '01/03/2012', '01/04/2011', '01/04/2012', '01/05/2011', '01/05/2012', '01/06/2011', '01/06/2012', '01/07/2011', '01/07/2012', '01/08/2011', '01/08/2012', '01/09/2011', '01/09/2012', '01/10/2011', '01/10/2012']

In [14]:
df["date"] = pd.to_datetime(df["date"], dayfirst=True, errors="coerce")
df["date_iso"] = df["date"].dt.strftime("%Y-%m-%d")

In [15]:
dates_evenements = ["2011-01-17", "2011-02-21"]

df.loc[df["date"].isin(dates_evenements), "is_special_event"] = 1

/tmp/ipykernel_474/1005888838.py:3: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  df.loc[df["date"].isin(dates_evenements), "is_special_event"] = 1

In [16]:
df["type_terrain"] = "indoor"

In [17]:
df["is_outdoor"] = df["type_terrain"].apply(lambda x: 1 if x == "outdoor" else 0)

In [22]:
df = df.drop(columns=[ "type_terrain", "is_indoor", "is_outdoor"], errors="ignore")

In [24]:
if 'is_special_event' not in df.columns:
    df['is_special_event'] = 0
df = df[[
    "date",
    "saison",
    "heure",
    "jour_semaine",
    "ferie",
    "jour_ouvrable",
    "meteo",
    "temperature",
    "humidite",
    "vent",
    "reservations",
    "is_special_event"
]]

KeyError: "['is_special_event'] not in index"

In [25]:
df["is_special_event"] = 0

In [26]:
dates_evenements = ["2011-01-17", "2011-02-21"]
df.loc[df["date"].isin(dates_evenements), "is_special_event"] = 1

/tmp/ipykernel_474/3386730025.py:2: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  df.loc[df["date"].isin(dates_evenements), "is_special_event"] = 1

In [27]:
df.isna().sum()

date                0
saison              0
heure               0
jour_semaine        0
ferie               0
jour_ouvrable       0
meteo               0
temperature         0
humidite            0
vent                0
reservations        0
is_special_event    0
dtype: int64

In [28]:
df.head()
print(df.columns.tolist())

['date', 'saison', 'heure', 'jour_semaine', 'ferie', 'jour_ouvrable', 'meteo', 'temperature', 'humidite', 'vent', 'reservations', 'is_special_event']

In [30]:
X = df[[
    "heure",
    "jour_semaine",
    "ferie",
    "jour_ouvrable",
    "meteo",
    "temperature",
    "humidite",
    "vent",
    "is_special_event"
]]

y = df["reservations"]

In [31]:
print(X.head())
print(y.head())
print(X.shape, y.shape)

   heure  jour_semaine  ferie  jour_ouvrable  meteo  temperature  humidite  \
0      0             6      0              0      1         0.24      0.81
1      1             6      0              0      1         0.22      0.80
2      2             6      0              0      1         0.22      0.80
3      3             6      0              0      1         0.24      0.75
4      4             6      0              0      1         0.24      0.75

   vent  is_special_event
0   0.0                 0
1   0.0                 0
2   0.0                 0
3   0.0                 0
4   0.0                 0
0    16
1    40
2    32
3    13
4     1
Name: reservations, dtype: int64
(17379, 9) (17379,)

In [32]:
df.to_csv("base_propre.csv", index=False)

In [33]:
from google.colab import files
files.download("base_propre.csv")